import "./globals.css";
import Header from "./navigation/header";
import Footer from "./navigation/footer";
import { Inter } from "next/font/google";


const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Talenin",
  description: "Generated by create next app",
  openGraph: {
    title: "Talenin",
    description: "Generated by create next app",
    url: "https://yourwebsite.com",
    siteName: "Talenin",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Talenin",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header />

        <layout className=""> {children}</layout>

        <Footer />
      </body>
    </html>
  );
}
